### ISSUE TITLE
Include your PCRE2 Build with my VBPCRE2 Wrapper

### ISSUE THREAD

**Issue by jpbro** [tannerhelland/PCRE2-VB6-DLL#1]
Hi Tanner,

Just wanted to ask about the protocol & licensing rules regarding including your binary and the original PCRE2 source in my VBPCRE2 wrapper. Can I/should I include a copy of your binary DLL in the Bin folder of my repository, and also include the original PCRE2 source in my Src folder? Or is it better/correct to just to link back to your repository for the binary and the PCRE2 webpage for the source?

No rush on this, and thanks for any advice you might have.

**Comment by tannerhelland** [comment]
Hi Jason.  Thank you for thinking of me!

To be honest, I don't think my work warrants any credit in this instance.  I just used CMake to produce a VB6-friendly VS2015 project, but I didn't contribute any unique code or changes to the base PCRE2 source.  Any credit should go directly to their homepage, I think, since anyone could use their original source to produce a project identical to this one.

Providing a binary DLL copy in your repository will certainly increase the chances of VB6 devs successfully using your library.  (In my experience, VB6 devs are not generally familiar with Git, so the easier you can make things for them, the better!)  No need to send them here to get a copy.

In fact, I don't know that I'd point anyone to this repository unless they specifically need to build the DLL differently.  (And honestly, if they know how to do that, they may as well grab the original PCRE source and start "from scratch".)

So my $0.02 is: ship the binary right there in your repository, and direct any credit back to the PCRE2 webpage.  If someone has specific questions about how your PCRE DLL was built, then I suppose you could send them here so they could see the config options we've activated to make the library as "VB6-friendly" as possible.

Congrats on reaching a stable release!

**Comment by jpbro** [comment]
Thanks Tanner, I appreciate your guidance and advice while I navigate this brave new world ;)

I also appreciate your contribution of the DLL - without it I wouldn't have even gotten started on the VBPCRE2 wrapper! I agree that I need to make things as easy as possible for the average dev, so I'll include your binary in my repository and link back to the PCRE2 web page for the source.

Cheers!
